module.exports = (dbinfo, Sequelize) => {
    return dbinfo.define(
        "article", {
            // field name
            id: {
                // set date type
                type: Sequelize.DataTypes.INTEGER,
                // set primaryKey
                primaryKey: true,
                // set autoIncrement
                autoIncrement: true
            },
            image: {
                // set data type with max length
                type: Sequelize.DataTypes.STRING(500),
                // setting allowNull to false will add NOT NULL to the column
                allowNull: false
            },
            // field name
            titre: {
                // set data type with max length
                type: Sequelize.DataTypes.STRING(65),
                // setting allowNull to false will add NOT NULL to the column
                allowNull: false
            },
            description: {
                // set data type with max length
                type: Sequelize.DataTypes.TEXT(),
                // setting allowNull to false will add NOT NULL to the column
                allowNull: false
            },

        }, {
            //TIMESTAMPS- Sequelize will add the attributes createdAt and updatedAt to your model so you will be able to know when the database entry went into the db and when it was updated last.
            //FALSE means no Created_at and updated_at
            timestamps: false,
            underscored: true
              /**
             * Sequelize allow setting underscored option for Model. When true this option will set the field option on all attributes to the underscored version of its name.
             * created_at
             * This also applies to foreign keys generated by associations.
             * */
        }
    );
};